name: Deploy to Neocities

on:
  push:
    branches:
      - main  # Ou 'master', dependendo da sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@v1
        with:
          api_token: ${{ secrets.NEOCITIES_API_KEY }}
          dist_dir: . # Opcional: Se seu site estiver dentro de uma pasta, ex: 'public'
          cleanup: true # Mude para 'true' para deletar arquivos no neocities que não estão no github
